// Code generated by command: go run asm.go -arch amd64,arm64 -out ../metro.s -stubs ../metro_stub.go -pkg metro. DO NOT EDIT.
// EXPERIMENTAL arm64 output lowered from an amd64 avo program.

//go:build arm64 && ((amd64 && gc && !purego && !noasm) || (arm64 && gc && !purego && !noasm))

#include "textflag.h"

// func Hash64(buffer []byte, seed uint64) uint64
TEXT ·Hash64(SB), NOSPLIT, $0-40
	MOVD seed+24(FP), R0
	MOVD buffer_base+0(FP), R1
	MOVD buffer_len+8(FP), R2
	MOVD $0xd6d018f5, R3
	MUL  R3, R0, R0
	MOVD $0x52bc33fedbe4cbb5, R3
	ADD  R3, R0, R0
	CMP  $0x20, R2
	BLT  after32
	MOVD R0, R3
	MOVD R0, R5
	MOVD R0, R6
	MOVD R0, R7

loop:
	MOVD (R1), R8
	MOVD $0xd6d018f5, R9
	MUL  R9, R8, R8
	ADD  R8, R3, R3
	ROR  $0x1d, R3, R3
	ADD  R6, R3, R3
	MOVD 8(R1), R8
	MOVD $0xa2aa033b, R9
	MUL  R9, R8, R8
	ADD  R8, R5, R5
	ROR  $0x1d, R5, R5
	ADD  R7, R5, R5
	MOVD 16(R1), R8
	MOVD $0x62992fc1, R9
	MUL  R9, R8, R8
	ADD  R8, R6, R6
	ROR  $0x1d, R6, R6
	ADD  R3, R6, R6
	MOVD 24(R1), R8
	MOVD $0x30bc5b29, R9
	MUL  R9, R8, R8
	ADD  R8, R7, R7
	ROR  $0x1d, R7, R7
	ADD  R5, R7, R7
	ADD  $0x20, R1, R1
	SUB  $0x20, R2, R2
	CMP  $0x20, R2
	BGE  loop
	MOVD R3, R8
	ADD  R7, R8, R8
	MOVD $0xd6d018f5, R9
	MUL  R9, R8, R8
	ADD  R5, R8, R8
	ROR  $0x25, R8, R8
	MOVD $0xa2aa033b, R9
	MUL  R9, R8, R8
	EOR  R8, R6, R6
	MOVD R5, R8
	ADD  R6, R8, R8
	MOVD $0xa2aa033b, R9
	MUL  R9, R8, R8
	ADD  R3, R8, R8
	ROR  $0x25, R8, R8
	MOVD $0xd6d018f5, R9
	MUL  R9, R8, R8
	EOR  R8, R7, R7
	MOVD R3, R8
	ADD  R6, R8, R8
	MOVD $0xd6d018f5, R9
	MUL  R9, R8, R8
	ADD  R7, R8, R8
	ROR  $0x25, R8, R8
	MOVD $0xa2aa033b, R9
	MUL  R9, R8, R8
	EOR  R8, R3, R3
	MOVD R5, R8
	ADD  R7, R8, R8
	MOVD $0xa2aa033b, R7
	MUL  R7, R8, R8
	ADD  R6, R8, R8
	ROR  $0x25, R8, R8
	MOVD $0xd6d018f5, R6
	MUL  R6, R8, R8
	EOR  R8, R5, R5
	EOR  R5, R3, R3
	ADD  R3, R0, R0

after32:
	CMP  $0x10, R2
	BLT  after16
	MOVD (R1), R3
	MOVD $0x62992fc1, R5
	MUL  R5, R3, R3
	ADD  R0, R3, R3
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x1d, R3, R3
	MOVD $0x30bc5b29, R5
	MUL  R5, R3, R3
	MOVD (R1), R5
	MOVD $0x62992fc1, R6
	MUL  R6, R5, R5
	ADD  R0, R5, R5
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x1d, R5, R5
	MOVD $0x30bc5b29, R6
	MUL  R6, R5, R5
	MOVD R3, R6
	MOVD $0xd6d018f5, R7
	MUL  R7, R6, R6
	ROR  $0x15, R6, R6
	ADD  R5, R6, R6
	EOR  R6, R3, R3
	MOVD R5, R6
	MOVD $0x30bc5b29, R7
	MUL  R7, R6, R6
	ROR  $0x15, R6, R6
	ADD  R3, R6, R6
	EOR  R6, R5, R5
	ADD  R5, R0, R0

after16:
	CMP  $0x08, R2
	BLT  after8
	MOVD (R1), R3
	MOVD $0x30bc5b29, R5
	MUL  R5, R3, R3
	ADD  R3, R0, R0
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x37, R0, R3
	MOVD $0xa2aa033b, R5
	MUL  R5, R3, R3
	EOR  R3, R0, R0

after8:
	CMP   $0x04, R2
	BLT   after4
	MOVD  $0, R3
	MOVWU (R1), R3
	MOVD  $0x30bc5b29, R5
	MUL   R5, R3, R3
	ADD   R3, R0, R0
	ADD   $0x04, R1, R1
	SUB   $0x04, R2, R2
	ROR   $0x1a, R0, R3
	MOVD  $0xa2aa033b, R5
	MUL   R5, R3, R3
	EOR   R3, R0, R0

after4:
	CMP   $0x02, R2
	BLT   after2
	MOVD  $0, R3
	MOVHU (R1), R16
	BFI   $0, R16, $16, R3
	MOVD  $0x30bc5b29, R5
	MUL   R5, R3, R3
	ADD   R3, R0, R0
	ADD   $0x02, R1, R1
	SUB   $0x02, R2, R2
	ROR   $0x30, R0, R3
	MOVD  $0xa2aa033b, R5
	MUL   R5, R3, R3
	EOR   R3, R0, R0

after2:
	CMP   $0x01, R2
	BLT   after1
	MOVBU (R1), R1
	MOVD  $0x30bc5b29, R2
	MUL   R2, R1, R1
	ADD   R1, R0, R0
	ROR   $0x25, R0, R1
	MOVD  $0xa2aa033b, R2
	MUL   R2, R1, R1
	EOR   R1, R0, R0

after1:
	ROR  $0x1c, R0, R1
	EOR  R1, R0, R0
	MOVD $0xd6d018f5, R1
	MUL  R1, R0, R0
	ROR  $0x1d, R0, R1
	EOR  R1, R0, R0
	MOVD R0, ret+32(FP)
	RET

// func Hash64Str(buffer string, seed uint64) uint64
TEXT ·Hash64Str(SB), NOSPLIT, $0-32
	MOVD seed+16(FP), R0
	MOVD buffer_base+0(FP), R1
	MOVD buffer_len+8(FP), R2
	MOVD $0xd6d018f5, R3
	MUL  R3, R0, R0
	MOVD $0x52bc33fedbe4cbb5, R3
	ADD  R3, R0, R0
	CMP  $0x20, R2
	BLT  after32
	MOVD R0, R3
	MOVD R0, R5
	MOVD R0, R6
	MOVD R0, R7

loop:
	MOVD (R1), R8
	MOVD $0xd6d018f5, R9
	MUL  R9, R8, R8
	ADD  R8, R3, R3
	ROR  $0x1d, R3, R3
	ADD  R6, R3, R3
	MOVD 8(R1), R8
	MOVD $0xa2aa033b, R9
	MUL  R9, R8, R8
	ADD  R8, R5, R5
	ROR  $0x1d, R5, R5
	ADD  R7, R5, R5
	MOVD 16(R1), R8
	MOVD $0x62992fc1, R9
	MUL  R9, R8, R8
	ADD  R8, R6, R6
	ROR  $0x1d, R6, R6
	ADD  R3, R6, R6
	MOVD 24(R1), R8
	MOVD $0x30bc5b29, R9
	MUL  R9, R8, R8
	ADD  R8, R7, R7
	ROR  $0x1d, R7, R7
	ADD  R5, R7, R7
	ADD  $0x20, R1, R1
	SUB  $0x20, R2, R2
	CMP  $0x20, R2
	BGE  loop
	MOVD R3, R8
	ADD  R7, R8, R8
	MOVD $0xd6d018f5, R9
	MUL  R9, R8, R8
	ADD  R5, R8, R8
	ROR  $0x25, R8, R8
	MOVD $0xa2aa033b, R9
	MUL  R9, R8, R8
	EOR  R8, R6, R6
	MOVD R5, R8
	ADD  R6, R8, R8
	MOVD $0xa2aa033b, R9
	MUL  R9, R8, R8
	ADD  R3, R8, R8
	ROR  $0x25, R8, R8
	MOVD $0xd6d018f5, R9
	MUL  R9, R8, R8
	EOR  R8, R7, R7
	MOVD R3, R8
	ADD  R6, R8, R8
	MOVD $0xd6d018f5, R9
	MUL  R9, R8, R8
	ADD  R7, R8, R8
	ROR  $0x25, R8, R8
	MOVD $0xa2aa033b, R9
	MUL  R9, R8, R8
	EOR  R8, R3, R3
	MOVD R5, R8
	ADD  R7, R8, R8
	MOVD $0xa2aa033b, R7
	MUL  R7, R8, R8
	ADD  R6, R8, R8
	ROR  $0x25, R8, R8
	MOVD $0xd6d018f5, R6
	MUL  R6, R8, R8
	EOR  R8, R5, R5
	EOR  R5, R3, R3
	ADD  R3, R0, R0

after32:
	CMP  $0x10, R2
	BLT  after16
	MOVD (R1), R3
	MOVD $0x62992fc1, R5
	MUL  R5, R3, R3
	ADD  R0, R3, R3
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x1d, R3, R3
	MOVD $0x30bc5b29, R5
	MUL  R5, R3, R3
	MOVD (R1), R5
	MOVD $0x62992fc1, R6
	MUL  R6, R5, R5
	ADD  R0, R5, R5
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x1d, R5, R5
	MOVD $0x30bc5b29, R6
	MUL  R6, R5, R5
	MOVD R3, R6
	MOVD $0xd6d018f5, R7
	MUL  R7, R6, R6
	ROR  $0x15, R6, R6
	ADD  R5, R6, R6
	EOR  R6, R3, R3
	MOVD R5, R6
	MOVD $0x30bc5b29, R7
	MUL  R7, R6, R6
	ROR  $0x15, R6, R6
	ADD  R3, R6, R6
	EOR  R6, R5, R5
	ADD  R5, R0, R0

after16:
	CMP  $0x08, R2
	BLT  after8
	MOVD (R1), R3
	MOVD $0x30bc5b29, R5
	MUL  R5, R3, R3
	ADD  R3, R0, R0
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x37, R0, R3
	MOVD $0xa2aa033b, R5
	MUL  R5, R3, R3
	EOR  R3, R0, R0

after8:
	CMP   $0x04, R2
	BLT   after4
	MOVD  $0, R3
	MOVWU (R1), R3
	MOVD  $0x30bc5b29, R5
	MUL   R5, R3, R3
	ADD   R3, R0, R0
	ADD   $0x04, R1, R1
	SUB   $0x04, R2, R2
	ROR   $0x1a, R0, R3
	MOVD  $0xa2aa033b, R5
	MUL   R5, R3, R3
	EOR   R3, R0, R0

after4:
	CMP   $0x02, R2
	BLT   after2
	MOVD  $0, R3
	MOVHU (R1), R16
	BFI   $0, R16, $16, R3
	MOVD  $0x30bc5b29, R5
	MUL   R5, R3, R3
	ADD   R3, R0, R0
	ADD   $0x02, R1, R1
	SUB   $0x02, R2, R2
	ROR   $0x30, R0, R3
	MOVD  $0xa2aa033b, R5
	MUL   R5, R3, R3
	EOR   R3, R0, R0

after2:
	CMP   $0x01, R2
	BLT   after1
	MOVBU (R1), R1
	MOVD  $0x30bc5b29, R2
	MUL   R2, R1, R1
	ADD   R1, R0, R0
	ROR   $0x25, R0, R1
	MOVD  $0xa2aa033b, R2
	MUL   R2, R1, R1
	EOR   R1, R0, R0

after1:
	ROR  $0x1c, R0, R1
	EOR  R1, R0, R0
	MOVD $0xd6d018f5, R1
	MUL  R1, R0, R0
	ROR  $0x1d, R0, R1
	EOR  R1, R0, R0
	MOVD R0, ret+24(FP)
	RET
