// Code generated by command: go run asm.go -arch amd64,arm64 -out ../metro.s -stubs ../metro_stub.go -pkg metro. DO NOT EDIT.
// EXPERIMENTAL arm64 output lowered from an amd64 avo program.

//go:build arm64 && ((amd64 && gc && !purego && !noasm) || (arm64 && gc && !purego && !noasm))

#include "textflag.h"

// func Hash64(buffer []byte, seed uint64) uint64
TEXT ·Hash64(SB), NOSPLIT, $0-40
	MOVD seed+24(FP), R0
	MOVD buffer_base+0(FP), R1
	MOVD buffer_len+8(FP), R2
	MOVD $0x00000000d6d018f5, R3
	MOVD $0x00000000a2aa033b, R5
	MOVD $0x0000000062992fc1, R6
	MOVD $0x0000000030bc5b29, R7
	MUL  R3, R0, R0
	MOVD $0x52bc33fedbe4cbb5, R8
	ADD  R8, R0, R0
	CMP  $0x20, R2
	BLT  after32
	MOVD R0, R8
	MOVD R0, R9
	MOVD R0, R10
	MOVD R0, R11

loop:
	MOVD (R1), R12
	MUL  R3, R12, R12
	ADD  R12, R8, R8
	ROR  $0x1d, R8, R8
	ADD  R10, R8, R8
	MOVD 8(R1), R12
	MUL  R5, R12, R12
	ADD  R12, R9, R9
	ROR  $0x1d, R9, R9
	ADD  R11, R9, R9
	MOVD 16(R1), R12
	MUL  R6, R12, R12
	ADD  R12, R10, R10
	ROR  $0x1d, R10, R10
	ADD  R8, R10, R10
	MOVD 24(R1), R12
	MUL  R7, R12, R12
	ADD  R12, R11, R11
	ROR  $0x1d, R11, R11
	ADD  R9, R11, R11
	ADD  $0x20, R1, R1
	SUB  $0x20, R2, R2
	CMP  $0x20, R2
	BGE  loop
	MOVD R8, R12
	ADD  R11, R12, R12
	MUL  R3, R12, R12
	ADD  R9, R12, R12
	ROR  $0x25, R12, R12
	MUL  R5, R12, R12
	EOR  R12, R10, R10
	MOVD R9, R12
	ADD  R10, R12, R12
	MUL  R5, R12, R12
	ADD  R8, R12, R12
	ROR  $0x25, R12, R12
	MUL  R3, R12, R12
	EOR  R12, R11, R11
	MOVD R8, R12
	ADD  R10, R12, R12
	MUL  R3, R12, R12
	ADD  R11, R12, R12
	ROR  $0x25, R12, R12
	MUL  R5, R12, R12
	EOR  R12, R8, R8
	MOVD R9, R12
	ADD  R11, R12, R12
	MUL  R5, R12, R12
	ADD  R10, R12, R12
	ROR  $0x25, R12, R12
	MUL  R3, R12, R12
	EOR  R12, R9, R9
	EOR  R9, R8, R8
	ADD  R8, R0, R0

after32:
	CMP  $0x10, R2
	BLT  after16
	MOVD (R1), R8
	MUL  R6, R8, R8
	ADD  R0, R8, R8
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x1d, R8, R8
	MUL  R7, R8, R8
	MOVD (R1), R9
	MUL  R6, R9, R9
	ADD  R0, R9, R9
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x1d, R9, R9
	MUL  R7, R9, R9
	MOVD R8, R6
	MUL  R3, R6, R6
	ROR  $0x15, R6, R6
	ADD  R9, R6, R6
	EOR  R6, R8, R8
	MOVD R9, R6
	MUL  R7, R6, R6
	ROR  $0x15, R6, R6
	ADD  R8, R6, R6
	EOR  R6, R9, R9
	ADD  R9, R0, R0

after16:
	CMP  $0x08, R2
	BLT  after8
	MOVD (R1), R6
	MUL  R7, R6, R6
	ADD  R6, R0, R0
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x37, R0, R6
	MUL  R5, R6, R6
	EOR  R6, R0, R0

after8:
	CMP   $0x04, R2
	BLT   after4
	MOVD  $0, R6
	MOVWU (R1), R6
	MUL   R7, R6, R6
	ADD   R6, R0, R0
	ADD   $0x04, R1, R1
	SUB   $0x04, R2, R2
	ROR   $0x1a, R0, R6
	MUL   R5, R6, R6
	EOR   R6, R0, R0

after4:
	CMP   $0x02, R2
	BLT   after2
	MOVD  $0, R6
	MOVHU (R1), R16
	BFI   $0, R16, $16, R6
	MUL   R7, R6, R6
	ADD   R6, R0, R0
	ADD   $0x02, R1, R1
	SUB   $0x02, R2, R2
	ROR   $0x30, R0, R6
	MUL   R5, R6, R6
	EOR   R6, R0, R0

after2:
	CMP   $0x01, R2
	BLT   after1
	MOVBU (R1), R1
	MUL   R7, R1, R1
	ADD   R1, R0, R0
	ROR   $0x25, R0, R1
	MUL   R5, R1, R1
	EOR   R1, R0, R0

after1:
	ROR  $0x1c, R0, R1
	EOR  R1, R0, R0
	MUL  R3, R0, R0
	ROR  $0x1d, R0, R1
	EOR  R1, R0, R0
	MOVD R0, ret+32(FP)
	RET

// func Hash64Str(buffer string, seed uint64) uint64
TEXT ·Hash64Str(SB), NOSPLIT, $0-32
	MOVD seed+16(FP), R0
	MOVD buffer_base+0(FP), R1
	MOVD buffer_len+8(FP), R2
	MOVD $0x00000000d6d018f5, R3
	MOVD $0x00000000a2aa033b, R5
	MOVD $0x0000000062992fc1, R6
	MOVD $0x0000000030bc5b29, R7
	MUL  R3, R0, R0
	MOVD $0x52bc33fedbe4cbb5, R8
	ADD  R8, R0, R0
	CMP  $0x20, R2
	BLT  after32
	MOVD R0, R8
	MOVD R0, R9
	MOVD R0, R10
	MOVD R0, R11

loop:
	MOVD (R1), R12
	MUL  R3, R12, R12
	ADD  R12, R8, R8
	ROR  $0x1d, R8, R8
	ADD  R10, R8, R8
	MOVD 8(R1), R12
	MUL  R5, R12, R12
	ADD  R12, R9, R9
	ROR  $0x1d, R9, R9
	ADD  R11, R9, R9
	MOVD 16(R1), R12
	MUL  R6, R12, R12
	ADD  R12, R10, R10
	ROR  $0x1d, R10, R10
	ADD  R8, R10, R10
	MOVD 24(R1), R12
	MUL  R7, R12, R12
	ADD  R12, R11, R11
	ROR  $0x1d, R11, R11
	ADD  R9, R11, R11
	ADD  $0x20, R1, R1
	SUB  $0x20, R2, R2
	CMP  $0x20, R2
	BGE  loop
	MOVD R8, R12
	ADD  R11, R12, R12
	MUL  R3, R12, R12
	ADD  R9, R12, R12
	ROR  $0x25, R12, R12
	MUL  R5, R12, R12
	EOR  R12, R10, R10
	MOVD R9, R12
	ADD  R10, R12, R12
	MUL  R5, R12, R12
	ADD  R8, R12, R12
	ROR  $0x25, R12, R12
	MUL  R3, R12, R12
	EOR  R12, R11, R11
	MOVD R8, R12
	ADD  R10, R12, R12
	MUL  R3, R12, R12
	ADD  R11, R12, R12
	ROR  $0x25, R12, R12
	MUL  R5, R12, R12
	EOR  R12, R8, R8
	MOVD R9, R12
	ADD  R11, R12, R12
	MUL  R5, R12, R12
	ADD  R10, R12, R12
	ROR  $0x25, R12, R12
	MUL  R3, R12, R12
	EOR  R12, R9, R9
	EOR  R9, R8, R8
	ADD  R8, R0, R0

after32:
	CMP  $0x10, R2
	BLT  after16
	MOVD (R1), R8
	MUL  R6, R8, R8
	ADD  R0, R8, R8
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x1d, R8, R8
	MUL  R7, R8, R8
	MOVD (R1), R9
	MUL  R6, R9, R9
	ADD  R0, R9, R9
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x1d, R9, R9
	MUL  R7, R9, R9
	MOVD R8, R6
	MUL  R3, R6, R6
	ROR  $0x15, R6, R6
	ADD  R9, R6, R6
	EOR  R6, R8, R8
	MOVD R9, R6
	MUL  R7, R6, R6
	ROR  $0x15, R6, R6
	ADD  R8, R6, R6
	EOR  R6, R9, R9
	ADD  R9, R0, R0

after16:
	CMP  $0x08, R2
	BLT  after8
	MOVD (R1), R6
	MUL  R7, R6, R6
	ADD  R6, R0, R0
	ADD  $0x08, R1, R1
	SUB  $0x08, R2, R2
	ROR  $0x37, R0, R6
	MUL  R5, R6, R6
	EOR  R6, R0, R0

after8:
	CMP   $0x04, R2
	BLT   after4
	MOVD  $0, R6
	MOVWU (R1), R6
	MUL   R7, R6, R6
	ADD   R6, R0, R0
	ADD   $0x04, R1, R1
	SUB   $0x04, R2, R2
	ROR   $0x1a, R0, R6
	MUL   R5, R6, R6
	EOR   R6, R0, R0

after4:
	CMP   $0x02, R2
	BLT   after2
	MOVD  $0, R6
	MOVHU (R1), R16
	BFI   $0, R16, $16, R6
	MUL   R7, R6, R6
	ADD   R6, R0, R0
	ADD   $0x02, R1, R1
	SUB   $0x02, R2, R2
	ROR   $0x30, R0, R6
	MUL   R5, R6, R6
	EOR   R6, R0, R0

after2:
	CMP   $0x01, R2
	BLT   after1
	MOVBU (R1), R1
	MUL   R7, R1, R1
	ADD   R1, R0, R0
	ROR   $0x25, R0, R1
	MUL   R5, R1, R1
	EOR   R1, R0, R0

after1:
	ROR  $0x1c, R0, R1
	EOR  R1, R0, R0
	MUL  R3, R0, R0
	ROR  $0x1d, R0, R1
	EOR  R1, R0, R0
	MOVD R0, ret+24(FP)
	RET
