// Code generated by command: go run asm.go -arch amd64,arm64 -out ../metro.s -stubs ../metro_stub.go -pkg metro. DO NOT EDIT.

//go:build (amd64 && gc && !purego && !noasm) || (arm64 && gc && !purego && !noasm)

package metro

//go:noescape
func Hash64(buffer []byte, seed uint64) uint64

func Hash64Str(buffer string, seed uint64) uint64
